# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: starwarssounds
    namespace: telegram
stringData:
    mysqlrootpassword: ENC[AES256_GCM,data:Pqn7,iv:ydBsxTNc6gXtjTnko4zNMcqhtJGl9wZU+AiiVbRcsjM=,tag:NVxf4Ye1hMnnOjKfzap/xQ==,type:str]
    mysqldatabase: ENC[AES256_GCM,data:Ha5T,iv:UtyVgkePLi0HG6wzz2/sSSpaukVw9jvcr0yoBtSxVsA=,tag:yWaXfNF1i+XU/PwmrhDGQw==,type:str]
    mysqluser: ENC[AES256_GCM,data:U2UE,iv:xoCS9kuHmqLSySUGQGrVrSKZveLjyCd9ocEcNp5rFAQ=,tag:UXyNJxs9r+++B3OOSPt38A==,type:str]
    mysqlpassword: ENC[AES256_GCM,data:nwpm,iv:SveNSDAIBlY1qDyRqlVoQsRztw5trqAaTGUgpO2ORD8=,tag:J/KmC6poTzlR+veKHw6G9Q==,type:str]
    telegramuseralias: ENC[AES256_GCM,data:AslRlob4,iv:XY4PtDcZkaFfD4xZaGnpA3Ahp9PxL0bylEVHJHqe0vI=,tag:s38e8+2nLQNoaGVEF06GOw==,type:str]
sops:
    age:
        - recipient: age1u9p8ypj39tla3pklmy3f9vract7ch3vhfpxarkggwrzlpc9w654s7c0vz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdXhHeHBkU2ttMXdZNlF3
            aHVTMGJvQnU0c2tVZzJuRWpHK3FER0g5eG1NCmkyQ1pqNi84eXZ4dFYxUFRURHg3
            TlpkZEMwVnpiQjRmMmRyRGNLbHpTVm8KLS0tIGpOQWdBZThYdWxpbmhnSUhiaVA1
            Q0c5NUdxdGl6TnVEZ0IxbEZ3YWJ1ckEKjWItYltzbD7WarCJRLLv//yZhsrwdWSG
            Mf3jF8tO1ct0X63zCtcpbxIEyNqP57nL+C+N2BjJLe1GJ97G01zcfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T14:16:01Z"
    mac: ENC[AES256_GCM,data:cZpA+AcKV1w9/SyVS4ME+md7rE56XlG7G7U2UUFNHWEi24kauiAa8qa60IBdPjjGV5vAcHlUnd7zH218+PgTr+urZ/aJkCU12mLfYQCI6Fw53uGsKuHDmVeYEp9bEGBKKztuo2UmlIN2iMrlLZpCw3N1E9Lstpo68k6nAuRMLpE=,iv:vH5zhDXMAImbShN0bEqxGY2KeWLKJ9V+lEUUZHRvkSs=,tag:THASUsZ6WqvmMtvwMZR7cg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
