# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: starwarssounds
    namespace: telegram
stringData:
    mysqlrootpassword: ENC[AES256_GCM,data:VBUN,iv:S6vpSAH5rUSCcr8VhCxJ8Y+g3w4dLst7qjHlYh+mAqE=,tag:pNy2ddecGurcIJi/XGD2qg==,type:str]
    mysqldatabase: ENC[AES256_GCM,data:8Z1G,iv:8HgElsdt4+CQcBdACFEe4gFgAPZEK4Hx2xXWg37jah4=,tag:2f1AfiI52zHS+wP9OHUYvg==,type:str]
    mysqluser: ENC[AES256_GCM,data:urHg,iv:VshJlDtsPrJfQdCeH6WLKqTDnqVtg0f4JIvYvf5WkAY=,tag:EY7tEvcXZJ3yCGn1swPr3A==,type:str]
    mysqlpassword: ENC[AES256_GCM,data:kB5a,iv:5K1aYasXVg6M7SsNm3WmAV344ovLeT2BHfDoKgOhDcY=,tag:k3au6zOo0PU1ZbxsXGDpWg==,type:str]
    telegramuseralias: ENC[AES256_GCM,data:u8B+oLLW,iv:/+XQJ2m7GL1C1qMCFI6tKDojxFYbGC1nY8T8d+U4zaE=,tag:5FhkO2kRTyNWTwuNCITXog==,type:str]
sops:
    age:
        - recipient: age1u9p8ypj39tla3pklmy3f9vract7ch3vhfpxarkggwrzlpc9w654s7c0vz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Uzc2ZDNTczVUay95SzJN
            NUJlMXZwMlM4U2hrWUtSM1k1UG9ha2YzUW1rCm5zaWxSbVlWRTNPZjdTQnd2MWxF
            dktlZlVkNUVQV2pSRW9IMTNSeUdsQXcKLS0tIEVSLzhKVWVkZHkvM0VmbzRiNFc5
            VGYzK2dTejMrR2dsMlJxM3l5cW5KNUUKdImzE37G8lqU0kRP69dsOAU4Ut2gwy9q
            qjEzdKlU9CFgtDuGolgiojU/VMqlPFRD4d0s8JzPBM71ZMiZjIcdig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T23:03:44Z"
    mac: ENC[AES256_GCM,data:X9U+koteQtZbzTWHYS7MWlWCMxVcDj7t+g+LanOYY7xSpQRmAcJUQOAghZ2KqU4pUIs3BIO7hcNiIgMgbDJ5a+lQblgZ1tAEDiyBxl3W6biaz0jXSS1gaPcAqxBNb2mLHgpalpMQVBA7WjVZpfMad/7kvWS7DjNEngBwAS8lDek=,iv:cO4p448Qc6bYEfsCRkksi4+VFjP8cCF/wDh0sFOTSm0=,tag:szO0va13AxHHoXPLWsdIzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
