# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:DMYlLy4n9rNxgQ==,iv:zApzmDReHj8y4hbjydKCAw8yJoZfGbNaeoMdhMdeeTI=,tag:BDrEi7rZtyaPGiKKxWtT4A==,type:str]
    SECRET_PLEX_CLAIM_TOKEN: ENC[AES256_GCM,data:ZtPsCSHR6hqedjQ/fpTCKjBFCRPeHdf/oHs=,iv:mQ7qoQy26iY6v35F+B4SlS5rxWXTrgS+yET2Np2bvxs=,tag:JRxfzcqn2Ljy/qqlXjra0Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:JFtAQSQqJXZyQfotx1t2WSJbySgLOh7Qda8skPuC,iv:GSoC8ZlDPT5bZ8MBrqlhHyrc8GkROlJhGiMgqINPMOw=,tag:jdbHqrv7nleRNVK1h0us5g==,type:str]
    SECRET_RAJOYBOT_TOKEN: ENC[AES256_GCM,data:ZUgL2f1bJt98aAsPD+aALjjqaYbvPLBXvB7/HE+RAAeeSeixbdVgllg+Niuu,iv:05ffVVTqpRy1ZtWo/i4qkaCTJQBjpktGmLpBASfeeGk=,tag:7eFo+7d4iJMPA1MdE7xGww==,type:str]
    SECRET_STARWARSSOUNDS_TOKEN: ENC[AES256_GCM,data:OLLCcnxtZXGXEhVwdin95bhDhKmZFiUQ7QSM3/jD6q3r52q6p9zPAR6bIJJ39Q==,iv:vpMjZWRHgvaXEMSINlZcd5QHKqvpi5+0dwPZ/E3cJ9w=,tag:4eteJxKmBhypTlh7pkGuhA==,type:str]
    SECRET_KINDLEBOT_TOKEN: ENC[AES256_GCM,data:4aeI0tZAzsGxCAHwu7M63lPDiXRbgWaCITznEKGHzKjjWBuw/bKMvldjw9Efhg==,iv:kzhb6jO+gLFbF/RqVNyI8GgMFR88wkJsDIx5/SY+VGc=,tag:/44CrCw6MdRgZuuQPsoiAg==,type:str]
    SECRET_GMVITABOT_TOKEN: ENC[AES256_GCM,data:UVX4HYDakwY/Tzyjj4iD6g5UO3Kx4ZCifJmggVh3vzofZYVhl478+uaCp52QFg==,iv:vfnQjMvMx0erNom9ZuWIi8VlshbjotW8uwtR2bE/laQ=,tag:6Ww0rcnhTX53r45BLQjahw==,type:str]
    MARIADBNEXTCLOUD_ROOT_PASS: ENC[AES256_GCM,data:Oar0KTNHeQHD8m6A3peLT6Ql4fI=,iv:pBOYn3LymoCF8gGV7tdBAoOwmGn9wB4R2au09F1Ic0s=,tag:09Ngl3bgLIM7p/rOTpYujg==,type:str]
    MARIADBNEXTCLOUD_DATABASE: ENC[AES256_GCM,data:fuglVcAMg+Zs,iv:qOyQl0EKX9CtuO0Y3w3WO43XmkJMZtDaqqIba7S0MzI=,tag:Evsfr5Mu3oTcdFWDfeEmYQ==,type:str]
    MARIADBNEXTCLOUD_USERNAME: ENC[AES256_GCM,data:DGl2+hhYg8Y/,iv:FCul5YWLnrnovl37LSeK209BhXWMcwvdTNV4HavcjBs=,tag:pUrVq2xa0XKuzhV1sx20sg==,type:str]
    MARIADBNEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:x+BSoJ2vE09+HNG0s3z1F0S82zc=,iv:tR7wEVQwIpQEdaveUNfQmhZYfD/21OjM0vPYd3wpWaA=,tag:GtBROzpvTXRKCov/O8r9KA==,type:str]
    POSTGRESQLFIREFLY_DATABASE: ENC[AES256_GCM,data:oW9q8fNV9Uut,iv:oRXhCiH7b2bRoQYdI73v010v05EV8Aqv7pdOI32UCKU=,tag:Nhfp98WcwscZsoT53HU1aA==,type:str]
    POSTGRESQLFIREFLY_USER: ENC[AES256_GCM,data:8ScIYMP/zQ==,iv:otgb+sWY4b3vTNQQZY8g4dqDSli27ew/2+1zV03NEmQ=,tag:Dzn02uGfm5xTqbBmXSGJ5Q==,type:str]
    POSTGRESQLFIREFLY_PASSWORD: ENC[AES256_GCM,data:dvAB50Rp3j0ni7mdExpWDIxOQjs=,iv:XHNAY+EL6SfMA8syo6yD4Pnu1JZwE7iRPa02c0yLdDE=,tag:FDiK3ZNBCftG1GZWsKd/cg==,type:str]
    SECRET_CROWDSEC_BOUNCER_API_KEY: ENC[AES256_GCM,data:M679m4jGkO6KLOs3Ijwsg8oJ6TTjLuKEl4cQh16kRAhnmzIje990xHgWlQ==,iv:CU5bgpwwewY9hlun7rLH1yzM2kQe+8dThgd/F5jbJqo=,tag:ZxQ9mSZUAcnNnRX+LgEyXA==,type:str]
    SECRET_CROWDSEC_URL: ENC[AES256_GCM,data:ZY6fURCtVFOWlDy8bjW0dNDeN9k+S/FJKVcMfIKCpyKWysSm,iv:jFdy8k4QCDgy4GQNOkYXUtI1EXWArG8efok/Qx+QlsM=,tag:OOWI6wEhrzPUq+ose09pvg==,type:str]
    SECRET_MIKROTIK_HOST: ENC[AES256_GCM,data:UHo/b68M6opwUycJNR7hVi0E,iv:oJP8L1yG9E1XbYkJrx5o5Wz+cTFUgMnkKiho2zIkwDg=,tag:7qAdSERlnnq/IBflOSQr5Q==,type:str]
    SECRET_MIKROTIK_USER: ENC[AES256_GCM,data:WSCUftntXRk=,iv:e9N3ssYbVY/PBhSrqhQzA9gnrQgsqxejqAWuyg5tc3I=,tag:NNIFutYKaH/sfiH2uFGVDQ==,type:str]
    SECRET_MIKROTIK_PASS: ENC[AES256_GCM,data:BehCxxRevE9QV4jIwLIwpbDJdtKK,iv:Jo8D8u3nthpNCPjE26PDZAjblRLvBp5X9isWCx15URI=,tag:QZT5Gy+iWcwbSnRSyx1a4Q==,type:str]
    CS_INSTANCE: ENC[AES256_GCM,data:a3x/UwPSctm+NKDPIA==,iv:dPPimwBbX7+UyzKXEIHU8/p/Rg9nLvZe2pjLyPII3H8=,tag:/VCrzsGgMD+ceEiPplDYmA==,type:str]
    CS_KEY: ENC[AES256_GCM,data:cXIy7jiP/awV6aMjpX43iQpqUrahlDbD7w==,iv:Wr8SeWZoiIr5Kt8ounKyYAKY7r/Tw7nGIXM72vGvEiM=,tag:WYW/fuFw6Beu563T5XN76A==,type:str]
sops:
    age:
        - recipient: age1u9p8ypj39tla3pklmy3f9vract7ch3vhfpxarkggwrzlpc9w654s7c0vz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidkt0aFNlVHVpTWhobU5j
            NTN4bDl1VGNDZ0dXTGhHOXBTT0pISTN4RlRnCkxkNmFIditlOVNsWjN0M3l5dXN4
            SkRSM3N6TFVXbHY2cHZFTEdVOHh0R3MKLS0tIGV2T1NkRlV1dUdHTDdkaVdLVE1l
            UGhWcDRNbXdpR1pyaHQrQ2hRSG5aL3cKbZeQEEqFSfe8CoyineDxyG+nFAW3AQFj
            XDY9FtWw6Us6x0jIUCL4OmXHBMWc2ZUVHneldR//eSBRuEgbqMKHMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T22:58:12Z"
    mac: ENC[AES256_GCM,data:TqHY+A3lBxNasu8dLjfvBppx23kSo409+/6hHZAYwWm6kR1bMFotFiQa7Mj47Y1gGW4E+VSVMbKXKvVC4iZ6mbz0gtwpogak2iOZ9AGU72F4WHnJC2CQndq8L/lvATdDgvzrUPZwzIpx/ugMf7SjVqjpd5390UbsdhvFB5vaHWQ=,iv:7q/c9uqkkY1SQK9lgnaTDPSqO5a8EzQL2OT24tRDSeQ=,tag:GxrD9GkB7Rm/r2f7CYiP+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
