# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:b5AlAS7f+3ZT8w==,iv:4gPToSBZfC0Nnycyo1KOo4fzKMsQ/HDiHGv8qTDdtYo=,tag:2Ewj4iU2jefB1cH7V464Qw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:JUoV4P1/Xyk5e0liI47rZdJ/RjvaIMc6t5CE7s/V,iv:t/hixC4NnFbc9bOq7bIXVdj5Pd5FCqOMFdnQSUrkQg0=,tag:BU3pPf9Zo9OCRIsAxEzDsA==,type:str]
    SECRET_RAJOYBOT_TOKEN: ENC[AES256_GCM,data:7FIhzYDFuhBGlr+a3YMeKHb5z3dxdQtk5PlwHAprJump6t4YHE1Uw3wqGHBn,iv:KILK8Ne37Ffrj0k9w1lWcm7gHJJS7ArmI/HqOt0wnfA=,tag:eQmuCh80g1JoQIA6Zj+SMQ==,type:str]
    SECRET_STARWARSSOUNDS_TOKEN: ENC[AES256_GCM,data:VlzUh0CalfvQDn/3iHI5zbm2XOKcPxFlJhy9mnKKAWbmxu4WaIYpxfmX1YcC+A==,iv:X2i08E1INrwK5WvlMJISNDrvfzxDFPNyGFaOLZBHb3Q=,tag:lMX2xvE9r4G/gM2rXjMZSA==,type:str]
    SECRET_KINDLEBOT_TOKEN: ENC[AES256_GCM,data:qrfRMzzE2h5x4Rd5ESZ0C9rZpwPMUadAO9aJH2IRpj4W1LyIH4ibuqznXNcUug==,iv:IdZKIs4sxmnHWoBQg7kYLXgt08/1jKCTHFtjmzJktZ8=,tag:BpzC6H79DygSS5JufhtLng==,type:str]
    SECRET_GMVITABOT_TOKEN: ENC[AES256_GCM,data:6NchML+Q6ycvYIOyOkYJreteUpryihWyyavrPqKadj1sg+SJic9MVlMq7EkYwA==,iv:Eeu4CUau2+Nuf0FHtshDZ3BWg5SFZIiSUCIPEhsi+oo=,tag:qPB2Y8xNbok4nZg8Rr0HVw==,type:str]
    MARIADBNEXTCLOUD_ROOT_PASS: ENC[AES256_GCM,data:c6kqwZ4T5oV7lm6M6thTbxxww6s=,iv:exO/3WZk3vNqsmYwNmsXt4/4LcOYs3mf7hG7Q03abco=,tag:arbACusYJrDqmQRSdHdthA==,type:str]
    MARIADBNEXTCLOUD_DATABASE: ENC[AES256_GCM,data:eWkCOmGF/ush,iv:XdKr7GsNliyevQSp3D6FXhLOBzLXIvuRxyoFiSErxnk=,tag:Em6uLS0i95w1cspDW2h2NA==,type:str]
    MARIADBNEXTCLOUD_USERNAME: ENC[AES256_GCM,data:rxp0lrHCM6Uq,iv:1Ssywa5g+AWbK9EiM1Wu95LihOVy1hpmxVvwgCekIyM=,tag:aNQEO0WUJbhpm/mSofw7LQ==,type:str]
    MARIADBNEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:7qFwgtyR/qlT9uugJ29GVS73Y8E=,iv:XUbBY9SWH2X79s84KDXQH8u3zPlzdZqednoWi+v6/R8=,tag:+J1m5SJX+OoL8WtU+2qREg==,type:str]
    SECRET_PLEX_CLAIM_TOKEN: ENC[AES256_GCM,data:FbTPIeIVuZ5OMeKbmBn5gkaFVCBw637EOMc=,iv:JM5TQg7uyEO0KoT58BXzGEtjGd7shj8sn8XD65fHY6s=,tag:ZIRrjl0pQa5Mt2Pb3fEd1g==,type:str]
    POSTGRESQLFIREFLY_DATABASE: ENC[AES256_GCM,data:G3ncw6WNeGQZ,iv:PLXaTfmE6JAjpCwZXG4i1gdJl9pHGGlSeIunElOzgiM=,tag:uD0tzyMHtiRgLLy32NIA2g==,type:str]
    POSTGRESQLFIREFLY_USER: ENC[AES256_GCM,data:eR+uzcN4TQ==,iv:i+Vo5KReM7PJHQG5BNuZAvqDsiF8GZixL+G0q3Jp53k=,tag:FGMQWUoyMBtOVBV+dlrjUA==,type:str]
    POSTGRESQLFIREFLY_PASSWORD: ENC[AES256_GCM,data:c2z2YpuM9jp+Gp2VPYeUXkCensU=,iv:Eh2X9M9T0A8WBfTsg0c7ZqvEU4a7iOmGj37YG4xhT/M=,tag:bgv88yfgeXb5UasFSDQbaQ==,type:str]
    SECRET_CROWDSEC_BOUNCER_API_KEY: ENC[AES256_GCM,data:Apm2vrLqS7rqjydmamlaGFMYgli4i1dNSeLcv2vvk3NRPW5rhP7cB+QlpQ==,iv:P9gH/CDIWZdXsxHLQ3+Oh3pV0BbZA1wt94J+8pEYWJQ=,tag:gv+OztF1cNnwHsIWj8OnOQ==,type:str]
    SECRET_CROWDSEC_URL: ENC[AES256_GCM,data:I06R+FdU0taYexGTiWY96ZZlPuPfxSkwqNsBvjpZ7bxAAIRW,iv:QAg+K3mfg2Q68FzBvB6vZzBn8ezk83DLDluEKh1nLS0=,tag:s7b3+wgzTcP/FhjcMfUxQQ==,type:str]
    SECRET_MIKROTIK_HOST: ENC[AES256_GCM,data:CfLUE94OVdmpVeVku9M3/8E/,iv:P4kaOfRr4TPa0/1A+uFUqHpOtshgaT0loORA3YfY3Kk=,tag:S5U+0mCV8GnYmEBAakwCEw==,type:str]
    SECRET_MIKROTIK_USER: ENC[AES256_GCM,data:NQ5XWZPSnFk=,iv:SAwXuNfYBSfxwP97mIWeDjzKaY2c/cnsX2TIbxIL+ds=,tag:uURdeVdAXAOQk2e2h6569Q==,type:str]
    SECRET_MIKROTIK_PASS: ENC[AES256_GCM,data:nkGH6yirJmigWqvLOXEiAV1+iq4h,iv:osHd68FLwZgw+7t5o9TGcHvz0td7I/ifeK/GDFk6HWo=,tag:CR7aVuyCmb95aOC6Ql7meg==,type:str]
    CS_INSTANCE: ENC[AES256_GCM,data:0cqSLWvCdDlYAkhn6g==,iv:pnZytdCkuPVA61uzLiG4RjdFafkwFe4J8GjNAMDaiWg=,tag:8i7Ip38A9P+NeJPxCaWWKg==,type:str]
    CS_KEY: ENC[AES256_GCM,data:z0rNOwVXdAynTD227j09AOahavIGyL/kXQ==,iv:1Q4WD2XqV7lZ8PQIFV/CgV/0Tm4ClxwgHo5CzTPcYzk=,tag:jcWXIz3rUxXsgbnJ9ep0nQ==,type:str]
sops:
    age:
        - recipient: age1u9p8ypj39tla3pklmy3f9vract7ch3vhfpxarkggwrzlpc9w654s7c0vz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3c2diWkpmUnk3M1JZa1Q2
            blNHV2UveDRDNXhTYTE3cVNGNWhoU2dhc0ZnClhRaW5GSGliWGo0dDIxSndTZ1RK
            a0hKM0V4alFYV01ic2VFQVNHN3c1NTAKLS0tIE1oVUUvVDNPRmdnSHc4cThwWHVO
            b0pVR0k2YWdRSEU1dTE2K0NWZEd0M0EKCZvBPYndMBsRhOOeikMzxurltnBM7V9T
            eZFBFr2b3sxiMckQXC9smHNml+td3vcDZ0vQSfPDR3ANaMeFTpfmmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T17:00:21Z"
    mac: ENC[AES256_GCM,data:yFaT3AY4KQ1qblsBk70cuv8LQqeWaJeMgX04PcVyR3DGITteFDP2lXwOjVflORWujJm/bFeMnywb86kGyQrWXpCT8Mur6aghvZoTieuREbEw+1ninVubAhnkE+TZ7r+9PqII8cBEPN1rgMAULeTWgLvisBrPtsaf/47i9veo8Jc=,iv:Qejk/JNpQnb76pcurYsNdDh2A4521hyqCrPgbbOfVPQ=,tag:S8qRwNpLNX+u8rWprKQlaA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
