# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:w0IxVCTsmZv94Q==,iv:LUSJhWblNnEamgcqtDN5Wtj596h2tbpSDV7y0301mrA=,tag:oERaPR6dkK5JlQXrfYIPlA==,type:str]
    SECRET_PLEX_CLAIM_TOKEN: ENC[AES256_GCM,data:m6TQUoh2DcH+TDNS0FR8pZtIPENIbeCMq6E=,iv:jURXsLq/XWPzwoUg+6b3eQOEWWEqGW15W0DNUwMdh5g=,tag:N0xiMWmL9bzWUDJyyLDUCA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Tz1Y/LtAVxS7Q2ufvUwe4caIS2fAvt9PyF9imPlR,iv:4un1MZ6keInxZNOjwPrQ1LyIrxrMRvdFPuAkFqDCYYM=,tag:9s/ZvR61/ksknPdf3DmIEA==,type:str]
    SECRET_RAJOYBOT_TOKEN: ENC[AES256_GCM,data:2IcPuA7icRUFOKGTeb2L6SBiR5o3EYxA4PvRe+sCTVrITXjR0A+0fphAMkgD,iv:e8irTujLtog+tGj9MidAnjuARAC7Xs2AVbMRdDXT8Cw=,tag:pCrkM0Xlp61g2xaqKD3NuQ==,type:str]
    SECRET_STARWARSSOUNDS_TOKEN: ENC[AES256_GCM,data:2DkWAd1jt+lCpGcGLTsyAh40ktuUaOSqXHLolLpjdioJ0vXkjwSTq1scr/porg==,iv:5mvvO/pPewE9b0sJYA/bkaGGIrqXDzJsMSOZseweDWM=,tag:lPUHkZaC4p3MiDdEjb7TOg==,type:str]
    SECRET_KINDLEBOT_TOKEN: ENC[AES256_GCM,data:TdGafnCkMDeZ/8JFroCdco9+J9HBRdwu96+T3DV+VCw6dxT+kp9D0zuhSS7zCQ==,iv:7gZDmGQa0qURKyWvJxY0vi5Bg5KrlCiXNhwQVT9iFsQ=,tag:D6DFvqslW0K9H0RUbS4wYA==,type:str]
    SECRET_GMVITABOT_TOKEN: ENC[AES256_GCM,data:JH1yTiydOyr88HrSJ7cMI+xirtgB+jcwMUnvylIg1OFz0SValOuCMkNWwgEzJw==,iv:9UxBekdDm36vvki+9vqLyrliqAg4GcEtZyCKPys90Gk=,tag:YrMpenteNStPoct+FfXPpA==,type:str]
    MARIADBNEXTCLOUD_ROOT_PASS: ENC[AES256_GCM,data:XilPZfH1vdn2wdE1nwQeETZzsqw=,iv:TAUnEZQTrtWFwX+SqOeYOhP2keAfMw/EbRHhkGVlSsE=,tag:k4SC52Uxw8576sa9gwtH8w==,type:str]
    MARIADBNEXTCLOUD_DATABASE: ENC[AES256_GCM,data:T3VlhNhTQ0VO,iv:UW6HkFwQX2hd0c7M/AB3Ehx4PrAoTkfVDGue8/X++yY=,tag:sOA4fMy+FrpDKZ+U8vwmAQ==,type:str]
    MARIADBNEXTCLOUD_USERNAME: ENC[AES256_GCM,data:GFI2m+xMN9Wu,iv:SSWn7+WJGx8DlIWp+xtJ+9h6E9H2lmcejJ9gfDl41tw=,tag:vsEW2EbUVgFEC0McmQcoMw==,type:str]
    MARIADBNEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:7aN0j/ZHeeg+vKaK64DQ33GVQUw=,iv:9QmgZ/s1gsEVIKNAmlNEV1JgUf7VClE4lTHqAICzExY=,tag:w53aARiQwpxPDC4AMxZ8yQ==,type:str]
    POSTGRESQLFIREFLY_DATABASE: ENC[AES256_GCM,data:gS3tlkcD0m+X,iv:bYHdEajRIupOe6uuobyZ9lklbq6aOdsKUZqwHxep5bs=,tag:SEsbOaLVrtRjXDgKOsYTAg==,type:str]
    POSTGRESQLFIREFLY_USER: ENC[AES256_GCM,data:siZuGWEL8g==,iv:6+DDTe4JxzeHQk2jALW6tSjx9rZqlpCr1zcMIOa8N4w=,tag:f6bf33x4BzeQHKN6mLXjsA==,type:str]
    POSTGRESQLFIREFLY_PASSWORD: ENC[AES256_GCM,data:8yT5jibcH1LzsiaQlj9Y9mZVJYc=,iv:Fttku1JmzKTI74La98/f8Prd0ZxDKXKB9ICwbjsvcko=,tag:K45Qr0YhVjFpWXErXu/etg==,type:str]
    SECRET_CROWDSEC_BOUNCER_API_KEY: ENC[AES256_GCM,data:Z4DkpT3Gy4idf8QyED1mzJ1LRhIufeKgFgdlvh8dL3os8PcOpGHzYmtdaw==,iv:92vx/oaiSKnstIPNtWZM7Hm69HB5knJjXf1H4ONUbt8=,tag:TIBXYw/cuskr+teOFkG35A==,type:str]
    SECRET_CROWDSEC_URL: ENC[AES256_GCM,data:BTvG9D6jz2gjuCvoa88JowH7A9rjVf2fec71FsT83XVQC8XD,iv:sZmZNB7HEUN3xkaJZmkGz7WuB+C0rg44PzcyCeIE5D4=,tag:pEhHdu/B+/6+xP3WsE39Mw==,type:str]
    SECRET_MIKROTIK_HOST: ENC[AES256_GCM,data:eDo4PIGp6DK7JdghEirG12+V,iv:vQux8DrNOfpPNqyDUAcP8V/Et2FGYh+CYQJnBrMMiiY=,tag:N/Aht5UDMncvSYDsFQ4PmA==,type:str]
    SECRET_MIKROTIK_USER: ENC[AES256_GCM,data:t2ZfLizHhyg=,iv:yCUxCUisM1ne4RaS4hVGxDTS6K6Wnw/yaWKt6z4RmS4=,tag:FJA8VuMToqWrc0hfgb3hNA==,type:str]
    SECRET_MIKROTIK_PASS: ENC[AES256_GCM,data:2F6hQzYAuIkwXreurHaTtT9omlmD,iv:Jil4dsymOZGaunfnNuRqEsNcrqDwfjLLk0K6UpOLqJc=,tag:0JUcHKf3SxRoc3NHvfhbyA==,type:str]
    CS_INSTANCE: ENC[AES256_GCM,data:V+K5I/IcOhymstqFkw==,iv:zAkhfGXBpPUrxrcgGz2zoXRBvYFu/NnTuVKj11eELdM=,tag:OHVN6kUYwgrL1QFMSHomLQ==,type:str]
    CS_KEY: ENC[AES256_GCM,data:lH9wC7I+seTp6NxSropf1qwa8ZbCg/6J9w==,iv:6I7RIbd5rLGPoQqBRaH/lZTOWpAukzSVGUbM9ngUomQ=,tag:Ty7Z4iqaYGGzCDbwnw5InQ==,type:str]
sops:
    age:
        - recipient: age1u9p8ypj39tla3pklmy3f9vract7ch3vhfpxarkggwrzlpc9w654s7c0vz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTkRSaDNPR3pUOFdKZ0xC
            bjFpRnJ0TmFMWEZCaEFQNHM5M0oxRkVXS0dJClpqSlJ5WmtTNXAxS0hIM3pFN0hh
            RE5tbTlGN0pFWHRyQkdRcUFGQkQ0K3MKLS0tIDZHNlZ3N3VvUkdvWEQ0a3pER0lr
            TTFrOFpxTk42YndDYU5aNGQrcWRsRWcKWy+sfdlrOPP0VUACeMAwZ8RlMYuW6vfS
            yQIf8S2gbOzBxsTExIeTvrcJi5QgIpH8SY3K7dPaXmTy590ViS8G1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:31:34Z"
    mac: ENC[AES256_GCM,data:GVoxYb+gD4r/OchCaUl1rzxb5mSzfLQr6QnbKjPj7CuBxpUnW74rvaVcVZNeXw3CVS7iBbUJZsUs3uxa56c+DNfojFoBRxs2oWZTmnz12IMmIyGm/gAoSWjwnfEZ5IId9dbQ5Ctsx7dmrg/yNo2rAu67NXmolJqksaW/8EErOA0=,iv:fCxqkMi/3B/1T+OXc4+ljiiUxjY8THnwW2VkExaJGDM=,tag:55bMSFhJPL1wSNhp3TtLMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
