# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: gmvitabot
    namespace: telegram
stringData:
    webhookhost: ENC[AES256_GCM,data:34SiwaGrefndG7tA6aTtnRBpsQroVM8wAwU5oRFgqc4=,iv:BpVBKwdzqyVysOFXrZrotq9ncpAaGNE4l+UARKqTu8I=,tag:rpsaK5W2QgYYXzmI8lZYYg==,type:str]
    webhookport: ENC[AES256_GCM,data:mhbq,iv:mojt8tQwMiMAO8Ouzq3dJ4u7k6AmGlVwK6jdkNjX3Ds=,tag:62P99CmNsWPeIMxStDil3Q==,type:str]
    admin: ENC[AES256_GCM,data:xj1rirMJ,iv:V4GiQCv9RvgXawovD9Wjy0ZMS5q1SeSdA+8E5GGhIKU=,tag:E2KeR6R4pvP3/ccE9bCaZQ==,type:str]
sops:
    age:
        - recipient: age1u9p8ypj39tla3pklmy3f9vract7ch3vhfpxarkggwrzlpc9w654s7c0vz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBud1VxZzlQaVR1dlltN1pi
            RjdNU3BjSXRtYXdDdFYrazZMQUhKVlkxR25ZCitxTVdwVy9xSDUveFZRY1BYTGZK
            SytIbjE1N0szNjE4QTdCTm9JOGhaS0kKLS0tIFF2K3NjZ0dpRXVHeElaMTJTUUNo
            Nk1IajJ4MkdDU1dVQTIzdjlSOWw0Qk0KGcCgjsNO+qtn/dtWuKPQTbkBAG1IMzNs
            VJJ9CX5dUazvjKCj41+3apDONoWu0KbOKkXZnLZaQUlr+nCVYm0QtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T21:22:29Z"
    mac: ENC[AES256_GCM,data:2g7tRiLhkvMjdPUzuCO9SVUpGk477pCeIwnlKmqrasF6BrxE/VoT0lGDv7JTC/pwifWPWwddjEu0SwhycuHpFngAGQmbuIo8uuilOnrubcmG6urvNWqrKmyeZox7KvupA3tLhNAuhAqoLTdJazQ0ZOjSoI8pvq7/df314JQxtV0=,iv:0+WKncGkLE5XlMHoGTPYr39ZnHRkAbfGbS/YYAk7IHo=,tag:MMD2DArSD3o3QbkXhb/fqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
