# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: gmvitabot
    namespace: telegram
stringData:
    webhookhost: ENC[AES256_GCM,data:XgRQ+2So2jU7XdgFFw9jb+R82tI85Xo=,iv:CUGQTF5RciLz2dUDw2UBzKu2b5PAc72waCeE3bpfO4M=,tag:LFbmeZ+Q8TmlH3N/WaFiSw==,type:str]
    webhookport: ENC[AES256_GCM,data:39aB,iv:A48ykzFh9mI6ygTxqFYmNIAsFiQifOkcRDt0+uC6AU0=,tag:fzsGjkZf9bPrwHm3Ij0cDw==,type:str]
    admin: ENC[AES256_GCM,data:0BDJf/0H,iv:LdADEuTjon8EG+4ihTrKI+lSzYab1tiHtL1mTFKXs68=,tag:F6UIuNKIpEbhL+9I5ViHyQ==,type:str]
sops:
    age:
        - recipient: age1u9p8ypj39tla3pklmy3f9vract7ch3vhfpxarkggwrzlpc9w654s7c0vz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3N0s1VkphOTJyWWRPeFUr
            dkRjTDF6ZEdiak5KRUFmMk1memdVaHZnaGg0Clp6TzY1RkVma2pjUk8vTFZRdUk0
            b2pBZDM3M28zTU1LdnVWUjdzWWFCVlkKLS0tIFFYR0dqeGR0cjNDalpQVzBEMnZr
            czNBdUVZcW9XeUtoTEpadkphVFBKSTAKvna/f0DZ0XLyis5zjxTs1iIGScQgzAAp
            qXIRP4xSqn6j87/YFAl1lwWTbiJpKJ9hUNc8rodg8JlkWYkeP8gDpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T22:38:57Z"
    mac: ENC[AES256_GCM,data:WwS1PilOD7d3boBhV0CTwSDy/3mL/SWpg7xzwOFoPnJllteVG2pDdrmpuHnq//yP9YvsSrZmtKRXg0JByiOJdnhvZn9J1U44K0yVsfZ6eOY1YjnvFLR2/sR9JB6t7c7lQL4JpxzcY2Tnnw3dwRUsy5hg4D7E9hZ49Ggw/J0TAz0=,iv:qmQUFQIXrFOtzgWsALVQ5RhbT4Fjp//wM08Pl+/gErA=,tag:kQ+46NFFnp9uclU7MV2yyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
