---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: home
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: nextcloud
  annotations:
    metallb.universe.tf/loadBalancerIPs: "${METALLB_NEXTCLOUD_ADDR}"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: nextcloud
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalTrafficPolicy: Local
