# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: scrutiny-secrets
    namespace: monitoring
stringData:
    SCRUTINY_NOTIFY_URLS: ENC[AES256_GCM,data:b/brCTFdabzSfphXzEh+GpybTK/44hpVE1b7mdb+IXzP0YzLSrp6FauLe//XJaMeaNXPGcI+JlJEjRLMCIs3h45IFfLahvp7fO5psb/HJdMOQ7oOhdJnIUjMgq/U,iv:lDwKHY7/EST0K96xlQyFRcg3j2iDx21d3BY7WGeud5I=,tag:iblffS2EaNoidqjlQOixFw==,type:str]
sops:
    age:
        - recipient: age1u9p8ypj39tla3pklmy3f9vract7ch3vhfpxarkggwrzlpc9w654s7c0vz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcDNiM2txMXZGbW5IY2hG
            VHZTMTJWMGtxamx1WDNPSzNiL3Y5a3l0S0VrCnZXSHk2ZUxuRTVsVEdubDdjMHBu
            UThEQ3N2c1ZZeEx5TERzRjhnNVNJRkUKLS0tIGVwbE5FVDNpZWtBa3VNbGJTcE0y
            WFRTSDR3MVRQTTFoWjc0VFVFQjJFbjQKiGDE3XtfsWyEY9JD7ENnXLvj5QaP1YsT
            q7UHUUvPrQvX2uNyPxT3zko+BQ+835nb4XseN+m7Qjorzei/ktXlaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:26:23Z"
    mac: ENC[AES256_GCM,data:gPcrEtZUWnPvpym6AXV/q8/oRZPR5N/b28fUBPfzT4C6yVSB46zWjwGlMIL4q0X+pOybYkc30JH4DUulbUPjMmR4LMETF0vBtmzAd9g+1qMJfmIhWReyYxwuty57Dlak4/SexIjxoI//UoiSKA04ETyWkiYcp1yCh4Bgt+JwkGI=,iv:aBqhE1zObMfMiiEvM9fX8W7cadGQv3PAclI0QkiqNuU=,tag:ZmS07DwkQQKyVOXOHxErrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
