# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: kindlebot
    namespace: telegram
stringData:
    telegramuseralias: ENC[AES256_GCM,data:xYwtKOsJd9fbfLO7NMlF8JCS0x4bcXx3o4b0g6AuarQdih0Jlk5LovJl1DOK/WoLVETEpXdG00CHbF38CTKvPw5xSsRDSHlG5TpArtaan17XbuV0u5TF7fxtX6lfcg7mbz1mQI0YcXy5c6CZABJHwpmaYlmePY+ps9WfyOO1GY5dBK++3Ygot7+WoAI=,iv:9xVoa8W1sCRhRT1tF7Zdy8g60lo5Vg9mGkvdtrxaAu8=,tag:ubHfmnQBllNt2bMptg0eBQ==,type:str]
    smtpserver: ENC[AES256_GCM,data:DBGx3AkqEHi1/ElbR7Q=,iv:7bJiVM1woU5QRANg/7SgSFZAfSvCsaReZS90sfUcUlM=,tag:aye/Vozgk16St0br8eioAg==,type:str]
    smtpport: ENC[AES256_GCM,data:UZHd,iv:B4u+ctS3a5E7areck4856ymDQ6QUCJltAVi96aryTBM=,tag:JYXZFYEKvvuJF1//+o8mCQ==,type:str]
    smtpuser: ENC[AES256_GCM,data:iRTZywJEs0nE6Mf0Grf0s8bjX2dzLwbGt2AaQg==,iv:VSwXZMAshOgXast8LJIHRPDRsJdCyfC50vcsJ7Ev5BA=,tag:trElhbSRpoynwWoGziOCbg==,type:str]
    smtppassword: ENC[AES256_GCM,data:nIFcTUDm/TWSEONTbU+Nu70IlA==,iv:e67Q9igi3rza0YFTslJVE1AMJbR//aIo7zV4AOleEwE=,tag:auLzNP7D5jpNoCF+PfVwzw==,type:str]
sops:
    age:
        - recipient: age1u9p8ypj39tla3pklmy3f9vract7ch3vhfpxarkggwrzlpc9w654s7c0vz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOS9wN3F4VG5KMFpTaVkv
            YjJEaGhEQ01KYis1NnowZEZ2RjBPcW1NSGxvCmhmbWFHbEhyRkdMNVJHRUJvV3Zw
            ZTl0dGV5YUMzN1RRa043RGxWVnpSdWsKLS0tIFc0aXFzRTh3MG5tcVh0OFJzeE82
            dzR1SEpXbjNsRmtCU1V4NVZiSW1DSm8Ky80jYYaGhUBTBm0LXQNzWK+LqkyxDxq5
            brd8khYPsaQyNYWsRwkFHu4QcbiCjFQb8cmb1HKo/SBrHYQ+OXSlmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T16:07:12Z"
    mac: ENC[AES256_GCM,data:/PU644yS6qOBNvCRVaPWyqe5ESPss1blpLJMTVwZchIQg5cMGMukYl/4PlOPQIHKACFKSWrkshblz9sL+f5YmKdu34JcRlMlIge8YBL/jxEuOZSk5Iy6axuBIegGrctszfIgXFsSAHYvLrMburPPnDmjAsJz99j2F7/w69ji+k0=,iv:Aw2dGXjoziYDdTuopKANoncgKpP53ufBnnYmUfidaMM=,tag:d5PBL1Dyt31Ku42B0b4g2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
