# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: kindlebot
    namespace: telegram
stringData:
    telegramuseralias: ENC[AES256_GCM,data:ZxoTlDeVx6+ZXGYNzAQ+DH1bzjDQu1qx77Gq1CFmsVC4ZwMyT+TWRYsZYYuzErks9MlXtHzbur+t+DxWr6zEvDgPFm46KKftsFa8xX/NJjWPYCjvnNV5ZNAa5MYG0zCNtURBMUI=,iv:yw9ClYQ6Zk66bgXhKGp6EaAZTjdWvy3pogGjns0Qlbw=,tag:oP5U70SiWpOSV8V7T4y/ZA==,type:str]
    smtpserver: ENC[AES256_GCM,data:X4p9+4Xb2X6ExBJ/ysE=,iv:rVyphsxbB2+iq/OG/EzjonCZemqrU6h/vaBtm+MyDvI=,tag:mt960BhoLuU9HuzFrv1KFg==,type:str]
    smtpport: ENC[AES256_GCM,data:QJcg,iv:koY4XCHLWiQ2D9UMofhmyfQr622ze61zMcEOFvhiWVg=,tag:rEaAcd9KFRJDfCCmROHR7w==,type:str]
    smtpuser: ENC[AES256_GCM,data:e1XnV4tPE3DYEenlS0PndRyBeSxYWN6H0FdUpQ==,iv:GH9Pa3nZhCJq6djU9N6Xon1BxanFdRyUYL40hyl+8cE=,tag:cqopposK2uY12QYR3GprOg==,type:str]
    smtppassword: ENC[AES256_GCM,data:h311PGd2hOpNKZfO6PSmBi07bw==,iv:o5Ku9bm7sriX+d3Y0ELOvv/HpsqgEEquPeHKquNh1ow=,tag:IdQzf7L6Bw2iXwPAXt4wpg==,type:str]
sops:
    age:
        - recipient: age1u9p8ypj39tla3pklmy3f9vract7ch3vhfpxarkggwrzlpc9w654s7c0vz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRStxc0J6cGlLWnRoQ1FU
            NVg3bHF2REtCZmtpclVJRnhNUS9DRTlFdTJnCm4xejhGd0VRWXMrN0lhWVkxRGlR
            bXhUclBqTThSQXdCZ2NRWlBIZjRKU0UKLS0tIFNZaG9STmdMdTIwSllpRVdGYmhs
            VHFIRlZwaDNadDQ5L3Bvb1hTM01ZazQKe22A8Tbbtm1SBtJ371sTW2e9c0R9PhlB
            MqIYCKky4Jm3dpMwtu9MbrF6BbFVJk/8g7snQsu0HoBVDlVhzEHi9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T22:23:30Z"
    mac: ENC[AES256_GCM,data:wwKZ2gITsUZ6q1+UFULWoo5XGVq0fz4w00jAFa2Kxk5QBEtijuJfN1gy0A/Gp8Bt+gojvHUsGEIDPBd16TK6P455B9rF5H3cS8M98qfd6TIAAkA6ZJj7kdkWbLtv0QcG9ZC96kAuBH8jkdFvYI32HMIHmZh33M+lBFNWjYZ8IKY=,iv:DlR1s92qQxi6q96n+4cBGtv3yVW+aTm8VFenSPLVAgE=,tag:TE1dGQmxQ3/t2krGaiNlIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
