# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: rajoybot
    namespace: telegram
stringData:
    telegramuseralias: ENC[AES256_GCM,data:znNmBZm6,iv:vVdtumEAithV8J0SUe9ET0xmGRhdDkoL7Mx2k0xaPmg=,tag:yOlVQ63c1jfoaX/7Rz1eOw==,type:str]
    webhookhost: ENC[AES256_GCM,data:tJiIYbhpehiOgPYZW80fu7Taa5vGlSA=,iv:WnL6Zqy4PCUP+AE/2HmHX7DpQwYjUj4GTIgCxfi8atM=,tag:u4H92r1whOUfVkWQYRv/Dw==,type:str]
    webhookport: ENC[AES256_GCM,data:Y1mh,iv:fhYPO6b3KGfpQL9Ch1n4oJ3/xZINI/lhmAQCGbu56MU=,tag:53f28BT275KLz/bgGY4D1g==,type:str]
sops:
    age:
        - recipient: age1u9p8ypj39tla3pklmy3f9vract7ch3vhfpxarkggwrzlpc9w654s7c0vz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQzNIa2FsdUZZeU91cVVC
            bUsyS2VreXlKdXJwK0t3V3hKRThac1I3WkZjCjNuYk92NWZnYlJBcjNJYU1IaWFO
            SnhkcUZoSTNXbFJ1QUhUQXFoemIwOWcKLS0tIDBhRVNwKzhyZkxpNFpFMlVFWTFC
            d0JabElMRUFVNDl2T0Y3TFR6c0xScnMKfBAPOCv++zCfKVAS+ogZhUjqcpdmFaCH
            wCr6b8n80wcvGKtV9k4RU+2YzV+m5KlvcK0m0fFo3CtEiT7fxFrzsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T20:56:33Z"
    mac: ENC[AES256_GCM,data:9GdRGs3MwJRS5PCHEkfwXiSyRjH8192lW3lse2LXZHplcB14wPoltbmrxF8y+BQkEPIJNAXceCf0EMq2OhBgTB1A9S07na7PcfCFj0+jhntl0FyUrifCVhOTQ1zahP/etzZoXijjxA4Y9ttY+USgZucShQ6KFENt/1CMYLGv6C0=,iv:1RttE8Wa/WGPGzNxFrG3osNv3gIFkVHlY9Yfnb97Nc8=,tag:uIAT7vJN7f0V9BQAQT/x5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
