# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: rajoybot
    namespace: telegram
stringData:
    mysqlrootpassword: ENC[AES256_GCM,data:IzkyZ4Grg7Q=,iv:C146Nn1Q47MQYHPlGC9Z/88RBg0FEXOKy0fZFIE20Y0=,tag:MrO8t3QY2DptYLdGP9o1WA==,type:str]
    mysqldatabase: ENC[AES256_GCM,data:CdazAN/re6E=,iv:y9fJZqKjh7kDcUenoqbWcKcQFvWYEbJZ/atKG92bl3I=,tag:sCCAQWQaNsqkL93+Hu1CMQ==,type:str]
    mysqluser: ENC[AES256_GCM,data:7hpnRmP5d68=,iv:qzOggj6lfiKskG2e4PEmpRuT6Bs7BY8z7P7JpA6Ewak=,tag:tiHI5aZcs6bb68R/sMpehA==,type:str]
    mysqlpassword: ENC[AES256_GCM,data:qZ9TEve0q20=,iv:X/6hU1U4NxEwmKMrGEGRHDh4SLs0JIVG5UW+LKTL9hw=,tag:Q8/rzSaT2goik0vd/6RniA==,type:str]
    telegramuseralias: ENC[AES256_GCM,data:Efi9aE65,iv:fhEHua64eqPJB2vo+ChDNlCeZ3waGlkvDg8RQUjTboE=,tag:SP2J38bSxGx25EpF+mUa4g==,type:str]
    webhookhost: ENC[AES256_GCM,data:8NVVZuYhSazkXqp2yNefPQGy7+QGO2s=,iv:pPEs/C9G7Y1XNDU5Ip2ddGeoLkRFiQUjt9jmczduA+Y=,tag:mopLvr5hKb3f27nojRGncQ==,type:str]
    webhookport: ENC[AES256_GCM,data:HvHF,iv:E0MHKddD1Y5+5SpUoRHgXr8G+ALkvGH9u7VbcP5GcwA=,tag:Re5WllsKMSA69v5ToGFbWw==,type:str]
sops:
    age:
        - recipient: age1u9p8ypj39tla3pklmy3f9vract7ch3vhfpxarkggwrzlpc9w654s7c0vz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MCs5aDZocUNKam1SejJo
            b0hJRUY1LzVqN2djNDNHSExuc21iZDA1U1RnCmc4WGVRcGEvUVNranhUWGxYZktD
            L0l6SEYxeURZYW5NZGVaWmdOQVN4MXcKLS0tIDhhbklqOWYzUjVRMGVHYm05cVlo
            YVU2K3pKazN5dmRqcEFnUWxVMDBBek0K4o2de5kpqH8QuM/FFrl8FDZtySJAASvv
            tSA5mwtQzn1/1P0Ru+XpxZio8NOUXZGLxjG4TM+ox6uPcqnFhALPbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T21:35:18Z"
    mac: ENC[AES256_GCM,data:D9g48EJF14RepL0lEzjaCDie7fYRd0cSeVK76oOqCbR9IFLEM9myCalB+0Kk3QUG9c6PA1+ENDetJ1aiFPy2nOBfRnZzNzEalNEgLqub63RKRNoz/d5O3sZRvrM68Zamnhin1GPq5VNXo7wH1LqSegptCPEJ4RcVTiynyxZNwsE=,iv:DCNd7N3zIODdoc13+ouhG6oF4ol2U4YGMGGumTHrYDA=,tag:vk017iW8oXJo4UASKptnaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
