apiVersion: v1
kind: Secret
metadata:
    name: github-api-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:luB2gn7iF30jY+JrUQsxbwftpKsjvla89iT6IbiJtdNrWVReTmGzyg==,iv:gD3JpXPW2pf8BNfNqYg60r2/RGnee/ZNXZNBMG042uQ=,tag:YLx7Eji0BTXXQ7qrCBUQEw==,type:str]
sops:
    age:
        - recipient: age1u9p8ypj39tla3pklmy3f9vract7ch3vhfpxarkggwrzlpc9w654s7c0vz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXKzF1YzdRc3dSSFA5elUz
            aFl4TlRQQ3JNaER1djdWNmUrQWd4b2lOcVJvCndsakVwRE1MQ3h5K1ppQkZBN0VD
            TC84cmhCdlBTOTBKcTRpc1RMV1p5ZlkKLS0tIDZDUVBmZXRiVDlxLzV2YVM2MmRo
            cTkwRFFFeHBPSzRDbnJ0RjJ4bVhEdFUKG0qrC/xn+EKtSZITmSaixT1RbP83P+W8
            QQWRDcFj3Pxm6EFLXlXfcELVAXf8uYK6RGDxah0mkDzpQKsX8P0JJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T22:12:48Z"
    mac: ENC[AES256_GCM,data:8QSVFyT2SHdvALBiRwYlgGL707mJhhoB54YtH9WHAojlfcYxxRogdZ0JPJgVud3o+yklRR8FrWUK+OshqPRfmHUWsX+2u5/2dTS1SyoXHSpbIky5E//a5oJwkjq/EvyAqMQqx6s/2t7/+OMiPBAuAFzr0MkHz8RiL3zDW2XUNew=,iv:oBrCiDlecWvsjXgvjxLvLl25ZfoHa+663UJhA634Axs=,tag:0ynfvqpZkT3wCpVNrAU3qg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
