---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: musicgrabber
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  install:
    createNamespace: true
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: g33kphr33k/musicgrabber
              tag: 2.5.2@sha256:2d20d5d2eb0c119b1b30e131af07bf8c29dc3fc6a445d7a5e3240ddf567ddc6f
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
              MUSIC_DIR: "/music"
              DB_PATH: "/data/music_grabber.db"
              ENABLE_MUSICBRAINZ: true
              DEFAULT_CONVERT_TO_FLAC: true
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: "internal"
        hosts:
          - host: &host "musicgrabber.internal.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /home/elraro/home-ops/volumes/musicgrabber/music
        globalMounts:
          - path: /music
      data:
        enabled: true
        type: hostPath
        hostPath: /home/elraro/home-ops/volumes/musicgrabber/data
        globalMounts:
          - path: /data
