---
name: KICS

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - master

jobs:
  build:
    name: KICS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Mkdir myResults
        run: mkdir -p myResults
      - name: run kics Scan
        uses: Checkmarx/kics-github-action@b974e53df1e3a2cd22ea90f0ec01882394feede4 # v2.1.20
        with:
          path: cluster
          output_path: myResults/
          output_formats: 'json,sarif'
          ignore_on_exit: results
          token: ${{ github.token }}
          enable_comments: true
      - name: Show results
        run: |
          cat myResults/results.sarif
          cat myResults/results.json
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@38697555549f1db7851b81482ff19f1fa5c4fedc # v4
        with:
          sarif_file: myResults/results.sarif
